version: "3.9"

services:

  data_ingestion:
    build:
      context: .
      dockerfile: ./services/backend/data_ingestion/Dockerfile
    image: bestseller/data_ingestion
    container_name: bestseller-data-ingestion-container
    ports:
      - "8001:8000"  # Porta externa 8001, interna 8000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=bestsellers

  db:
    image: postgres:15
    container_name: bestseller-postgres_db-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bestsellers
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - db_data:/var/lib/postgresql/data
      - ./services/database/scripts:/docker-entrypoint-initdb.d

  frontend:
    build:
      context: .
      dockerfile: services/frontend/Dockerfile
    image: bestseller/streamlit
    container_name: bestseller-streamlit-container
    ports:
      - "8501:8501"
    # volumes:
    #   - .:/app
    # depends_on:
    #   - mock-backend
    environment:
      # - ENDPOINT_URL=http://mock-backend
      # - ENDPOINT_PORT=8000
      # - ENDPOINT_INFERENCIA=/inferir
      # - ENDPOINT_TREINAMENTO=/treinar
      # - ENDPOINT_INGESTAO=/ingest
      - SHOW_TEST_BUTTON=true
      # - PYTHONUNBUFFERED=1

  model_training:
    build:
      context: .
      dockerfile: ./services/backend/model_training/Dockerfile
    image: bestseller/model_training
    container_name: bestseller-model-training-container
    volumes:
      # Mapeia a pasta local de artefatos para dentro do container
      - ./services/backend/trained_models:/services/trained_models
      - ./services/backend/model_training/src:/app/src
    # depends_on:
      # - db
    # Exemplo de comando para rodar o uvicorn e expor o servi�o de treinamento (ajuste conforme necess�rio)
    # command: uvicorn services.backend.model_training.src.train:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8000"  # Porta externa 8002, interna 8000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=bestsellers

  # inferencia:
  #   build: ./inference
  #   command: ["python", "infer.py"]
  #   depends_on:
  #     - db

  mock-backend:
    build:
      context: .
      dockerfile: ./services/frontend/tests/Dockerfile
    image: bestseller/mock-backend
    container_name: bestseller-mock-backend-container
    ports:
      - "8000:8000"  # Porta externa 8000, interna 8000

volumes:
  pgdata:
